name: 📈 台期所完整資料爬取

on:
  schedule:
    # 台灣時間下午3點半 = UTC時間上午7點半 (UTC+8)
    - cron: '30 7 * * 1-5'  # 週一到週五 UTC 07:30 (台灣時間 15:30)
  workflow_dispatch:  # 允許手動觸發

jobs:
  crawl-complete-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🔄 檢出程式碼
      uses: actions/checkout@v4
    
    - name: 🐍 設定Python環境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: 📦 安裝相依套件
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 🕐 顯示當前時間
      run: |
        echo "UTC時間: $(date -u)"
        echo "台灣時間: $(TZ='Asia/Taipei' date)"
    
    - name: 📈 爬取完整資料
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python taifex_crawler.py \
          --date-range today \
          --contracts TX,TE,MTX,ZMX,NQF \
          --identities ALL \
          --data_type COMPLETE \
          --max_workers 5 \
          --delay 1.0 \
          --check_days 7
    
    - name: 📁 上傳爬取結果
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: complete-data-results
        path: |
          output/*.csv
          output/*.xlsx
          charts/*.png
          *.log
        retention-days: 30
    
    - name: 💬 發送通知 (成功)
      if: success()
      run: |
        echo "✅ 完整資料爬取成功 - $(TZ='Asia/Taipei' date)"
        echo "📊 完整資料已上傳到Google Sheets的「完整資料」分頁"
        echo "🎨 圖表已生成並發送到Telegram"
    
    - name: 💬 發送通知 (失敗)
      if: failure()
      run: |
        echo "❌ 完整資料爬取失敗 - $(TZ='Asia/Taipei' date)"
        echo "請檢查日誌了解詳細錯誤信息" 